//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHiTech
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookOrder
    {
        public int CustomerOrderID { get; set; }
        public int BookID { get; set; }
        public int OrderQuality { get; set; }
    
        public virtual bookDetail bookDetail { get; set; }
        public virtual customerOrder customerOrder { get; set; }
    }
}
