//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHiTech
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int invoiceID { get; set; }
        public int totalPrice { get; set; }
        public System.DateTime paymentDate { get; set; }
        public string typeOfPayment { get; set; }
    }
}
