//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHiTech
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HitechProjectEntities3 : DbContext
    {
        public HitechProjectEntities3()
            : base("name=HitechProjectEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bookDetail> bookDetails { get; set; }
        public virtual DbSet<bookOrder> bookOrders { get; set; }
        public virtual DbSet<customerDetail> customerDetails { get; set; }
        public virtual DbSet<customerOrder> customerOrders { get; set; }
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<bookData> bookDatas { get; set; }
        public virtual DbSet<supplierData> supplierDatas { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
    }
}
